### ISSUE TITLE
Remove `pkg` directory

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/sdk#47]
WDYT about moving everything under `pkg` up a level, so it's `chainguard.dev/sdk/auth/aws`, `chainguard.dev/sdk/events/admission`, `chainguard.dev/sdk/uidp`, etc.?

There's no conflict with `proto`, and it makes importpaths a little smaller and tidier. I'm not sure what kind of downstream breakages/refactors this would entail, but it's probably easier to do it now than later, if we ever want to do it.

**Comment by cmdpdx** [comment]
Good call out, I didn't consider this when moving out of `mono`. I have a PR I'm working on that switches refs in mono to use the public sdk. I've held off since @hectorj2f mentioned he had a proto change he wanted to get in before a new release of sdk. I can make this directory change and roll the path changes into my mono PR.

**Comment by hectorj2f** [comment]
My PRs got merged. So I am good, as long as we use the sdk latest version of main.
